name: social_life_app
description: A modern social media app with AI-powered personal assistant features
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Navigation
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  image_picker: ^1.0.4
  photo_view: ^0.14.0
  flutter_staggered_grid_view: ^0.7.0
  
  # State Management
  provider: ^6.1.1
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9
  
  # Database & Storage
  sqflite: ^2.3.0
  sqflite_common_ffi_web: ^0.4.2+2
  path: ^1.8.3
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  
  # Network & API
  http: ^1.1.0
  dio: ^5.3.2
  
  # Authentication
  # firebase_core: ^3.6.0
  # firebase_auth: ^5.3.1
  # google_sign_in: ^6.2.0
  # firebase_storage: ^11.5.6
  # cloud_firestore: ^4.13.6
  
  # Calendar & Date
  table_calendar: ^3.0.9
  intl: ^0.18.1
  
  # Chat & Communication
  flutter_chat_ui: ^1.6.10
  uuid: ^4.2.1
  
  # AI & RAG Features
  vector_math: ^2.1.4
  
  # Utils
  permission_handler: ^11.1.0
  device_info_plus: ^9.1.1
  package_info_plus: ^4.2.0
  crypto: ^3.0.3
  
  # Video & Media
  video_player: ^2.8.1
  camera: ^0.10.5+5
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
  
  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: assets/fonts/Inter-Regular.ttf
  #       - asset: assets/fonts/Inter-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Inter-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Inter-Bold.ttf
  #         weight: 700